services:
  web:
    restart: always
    depends_on:
      - postgresql
      - pgbouncer
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres@pgbouncer:6432/postgres
    ports:
     - "5000:5000"
    volumes:
     - .:/app
  postgresql:
    image: postgres
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  pgbouncer:
    image: docker.io/bitnami/pgbouncer
    expose:
      - 6432
    ports:
      - 6432:6432
    environment:
      - POSTGRESQL_HOST=postgresql
      - PGBOUNCER_AUTH_TYPE=trust

    # to use custom config 
    # volumes:
    #   - /path/to/pgbouncer-persistence/conf/:/bitnami/pgbouncer/conf/
volumes:
  postgresql_data:
    driver: local